//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSHOP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1394/01/01-1394/01/01")]
        public string ViewSaleFactors {
            get {
                return ((string)(this["ViewSaleFactors"]));
            }
            set {
                this["ViewSaleFactors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ViewOrders {
            get {
                return ((string)(this["ViewOrders"]));
            }
            set {
                this["ViewOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ViewBuyFactors {
            get {
                return ((string)(this["ViewBuyFactors"]));
            }
            set {
                this["ViewBuyFactors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string SaleDocument {
            get {
                return ((string)(this["SaleDocument"]));
            }
            set {
                this["SaleDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string BuyDocument {
            get {
                return ((string)(this["BuyDocument"]));
            }
            set {
                this["BuyDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ViewReturnSale {
            get {
                return ((string)(this["ViewReturnSale"]));
            }
            set {
                this["ViewReturnSale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ViewReturnBuy {
            get {
                return ((string)(this["ViewReturnBuy"]));
            }
            set {
                this["ViewReturnBuy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ViewServiceFactors {
            get {
                return ((string)(this["ViewServiceFactors"]));
            }
            set {
                this["ViewServiceFactors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCustomerBill {
            get {
                return ((bool)(this["ShowCustomerBill"]));
            }
            set {
                this["ShowCustomerBill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Box")]
        public string AwardCompute {
            get {
                return ((string)(this["AwardCompute"]));
            }
            set {
                this["AwardCompute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalePriceCompute {
            get {
                return ((bool)(this["SalePriceCompute"]));
            }
            set {
                this["SalePriceCompute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color BackColor {
            get {
                return ((global::System.Drawing.Color)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short SaleFactorStyle {
            get {
                return ((short)(this["SaleFactorStyle"]));
            }
            set {
                this["SaleFactorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short BuyFactorStyle {
            get {
                return ((short)(this["BuyFactorStyle"]));
            }
            set {
                this["BuyFactorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short ReturnBuyFactorStyle {
            get {
                return ((short)(this["ReturnBuyFactorStyle"]));
            }
            set {
                this["ReturnBuyFactorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short PrefactorStyle {
            get {
                return ((short)(this["PrefactorStyle"]));
            }
            set {
                this["PrefactorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short ReturnSaleFactor {
            get {
                return ((short)(this["ReturnSaleFactor"]));
            }
            set {
                this["ReturnSaleFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short OrderStyle {
            get {
                return ((short)(this["OrderStyle"]));
            }
            set {
                this["OrderStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaleDescription {
            get {
                return ((string)(this["SaleDescription"]));
            }
            set {
                this["SaleDescription"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=P-RDP\\PERP2017;Initial Catalog=PERP_MAIN;Persist Security Info=True;U" +
            "ser ID=sa;Password=Pars@63")]
        public string MAIN {
            get {
                //return ((string)(this["MAIN"]));
                return Class_ChangeConnectionString.SetConnection("PERP_MAIN");
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrefactorDescription {
            get {
                return ((string)(this["PrefactorDescription"]));
            }
            set {
                this["PrefactorDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShowPriceAlert {
            get {
                return ((int)(this["ShowPriceAlert"]));
            }
            set {
                this["ShowPriceAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCalculateGiftDuringSave {
            get {
                return ((bool)(this["ShowCalculateGiftDuringSave"]));
            }
            set {
                this["ShowCalculateGiftDuringSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DontShowLogo {
            get {
                return ((bool)(this["DontShowLogo"]));
            }
            set {
                this["DontShowLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterReturnSaleFactorWithGoods {
            get {
                return ((bool)(this["RegisterReturnSaleFactorWithGoods"]));
            }
            set {
                this["RegisterReturnSaleFactorWithGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterBuyFactorWithGoods {
            get {
                return ((bool)(this["RegisterBuyFactorWithGoods"]));
            }
            set {
                this["RegisterBuyFactorWithGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterReturnBuyFactorWithGoods {
            get {
                return ((bool)(this["RegisterReturnBuyFactorWithGoods"]));
            }
            set {
                this["RegisterReturnBuyFactorWithGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterSaleFactorWithGoods {
            get {
                return ((bool)(this["RegisterSaleFactorWithGoods"]));
            }
            set {
                this["RegisterSaleFactorWithGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AggregationSaleDoc {
            get {
                return ((bool)(this["AggregationSaleDoc"]));
            }
            set {
                this["AggregationSaleDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short LegalFactorPrintLayout {
            get {
                return ((short)(this["LegalFactorPrintLayout"]));
            }
            set {
                this["LegalFactorPrintLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short ServiceFactorPrintLayout {
            get {
                return ((short)(this["ServiceFactorPrintLayout"]));
            }
            set {
                this["ServiceFactorPrintLayout"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.mehrafraz.com/webservice/service.asmx")]
        public string PSALE_com_mehrafraz_www_Service {
            get {
                return ((string)(this["PSALE_com_mehrafraz_www_Service"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveACCRemain {
            get {
                return ((string)(this["SaveACCRemain"]));
            }
            set {
                this["SaveACCRemain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowChangePriceInSale {
            get {
                return ((bool)(this["ShowChangePriceInSale"]));
            }
            set {
                this["ShowChangePriceInSale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyFactorPriceCompute {
            get {
                return ((bool)(this["BuyFactorPriceCompute"]));
            }
            set {
                this["BuyFactorPriceCompute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReturnSalePriceCompute {
            get {
                return ((bool)(this["ReturnSalePriceCompute"]));
            }
            set {
                this["ReturnSalePriceCompute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReturnBuyFactorPriceCompute {
            get {
                return ((bool)(this["ReturnBuyFactorPriceCompute"]));
            }
            set {
                this["ReturnBuyFactorPriceCompute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string BalanceNum {
            get {
                return ((string)(this["BalanceNum"]));
            }
            set {
                this["BalanceNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Ware {
            get {
                return ((string)(this["Ware"]));
            }
            set {
                this["Ware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Masool {
            get {
                return ((string)(this["Masool"]));
            }
            set {
                this["Masool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaleValue {
            get {
                return ((bool)(this["SaleValue"]));
            }
            set {
                this["SaleValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleAmount {
            get {
                return ((bool)(this["SaleAmount"]));
            }
            set {
                this["SaleAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleDesc {
            get {
                return ((bool)(this["SaleDesc"]));
            }
            set {
                this["SaleDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleEtebar {
            get {
                return ((bool)(this["SaleEtebar"]));
            }
            set {
                this["SaleEtebar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleNetPrice {
            get {
                return ((bool)(this["SaleNetPrice"]));
            }
            set {
                this["SaleNetPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleTotalAmount {
            get {
                return ((bool)(this["SaleTotalAmount"]));
            }
            set {
                this["SaleTotalAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleSumDiscount {
            get {
                return ((bool)(this["SaleSumDiscount"]));
            }
            set {
                this["SaleSumDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleSumExtra {
            get {
                return ((bool)(this["SaleSumExtra"]));
            }
            set {
                this["SaleSumExtra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleCustomer {
            get {
                return ((bool)(this["SaleCustomer"]));
            }
            set {
                this["SaleCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleWare {
            get {
                return ((bool)(this["SaleWare"]));
            }
            set {
                this["SaleWare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleFunc {
            get {
                return ((bool)(this["SaleFunc"]));
            }
            set {
                this["SaleFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyValue {
            get {
                return ((bool)(this["BuyValue"]));
            }
            set {
                this["BuyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyAmount {
            get {
                return ((bool)(this["BuyAmount"]));
            }
            set {
                this["BuyAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyDesc {
            get {
                return ((bool)(this["BuyDesc"]));
            }
            set {
                this["BuyDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyEtebar {
            get {
                return ((bool)(this["BuyEtebar"]));
            }
            set {
                this["BuyEtebar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyNetPrice {
            get {
                return ((bool)(this["BuyNetPrice"]));
            }
            set {
                this["BuyNetPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyTotalAmount {
            get {
                return ((bool)(this["BuyTotalAmount"]));
            }
            set {
                this["BuyTotalAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuySumDiscount {
            get {
                return ((bool)(this["BuySumDiscount"]));
            }
            set {
                this["BuySumDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuySumExtra {
            get {
                return ((bool)(this["BuySumExtra"]));
            }
            set {
                this["BuySumExtra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyCustomer {
            get {
                return ((bool)(this["BuyCustomer"]));
            }
            set {
                this["BuyCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyWare {
            get {
                return ((bool)(this["BuyWare"]));
            }
            set {
                this["BuyWare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyFunc {
            get {
                return ((bool)(this["BuyFunc"]));
            }
            set {
                this["BuyFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaleNum {
            get {
                return ((bool)(this["SaleNum"]));
            }
            set {
                this["SaleNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaleDate {
            get {
                return ((bool)(this["SaleDate"]));
            }
            set {
                this["SaleDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BuyNum {
            get {
                return ((bool)(this["BuyNum"]));
            }
            set {
                this["BuyNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BuyDate {
            get {
                return ((bool)(this["BuyDate"]));
            }
            set {
                this["BuyDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyCondition {
            get {
                return ((bool)(this["BuyCondition"]));
            }
            set {
                this["BuyCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleCondition {
            get {
                return ((bool)(this["SaleCondition"]));
            }
            set {
                this["SaleCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterSaleFactorNoteGoods {
            get {
                return ((bool)(this["RegisterSaleFactorNoteGoods"]));
            }
            set {
                this["RegisterSaleFactorNoteGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool whtoutgoods {
            get {
                return ((bool)(this["whtoutgoods"]));
            }
            set {
                this["whtoutgoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaleType {
            get {
                return ((string)(this["SaleType"]));
            }
            set {
                this["SaleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterBuyFactorNoteGoods {
            get {
                return ((bool)(this["RegisterBuyFactorNoteGoods"]));
            }
            set {
                this["RegisterBuyFactorNoteGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chksanadPerson {
            get {
                return ((bool)(this["chksanadPerson"]));
            }
            set {
                this["chksanadPerson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int printorder {
            get {
                return ((int)(this["printorder"]));
            }
            set {
                this["printorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Function {
            get {
                return ((string)(this["Function"]));
            }
            set {
                this["Function"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Project {
            get {
                return ((string)(this["Project"]));
            }
            set {
                this["Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Customer {
            get {
                return ((string)(this["Customer"]));
            }
            set {
                this["Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkInclude {
            get {
                return ((bool)(this["chkInclude"]));
            }
            set {
                this["chkInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkseprate {
            get {
                return ((bool)(this["chkseprate"]));
            }
            set {
                this["chkseprate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string SaleReport_Customer {
            get {
                return ((string)(this["SaleReport_Customer"]));
            }
            set {
                this["SaleReport_Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string SaleReport_Goods {
            get {
                return ((string)(this["SaleReport_Goods"]));
            }
            set {
                this["SaleReport_Goods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ReturnSaleReport_Customer {
            get {
                return ((string)(this["ReturnSaleReport_Customer"]));
            }
            set {
                this["ReturnSaleReport_Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ReturnSaleReport_Good {
            get {
                return ((string)(this["ReturnSaleReport_Good"]));
            }
            set {
                this["ReturnSaleReport_Good"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ExtraReduction {
            get {
                return ((string)(this["ExtraReduction"]));
            }
            set {
                this["ExtraReduction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string DiscountReport {
            get {
                return ((string)(this["DiscountReport"]));
            }
            set {
                this["DiscountReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string CustomerGoods {
            get {
                return ((string)(this["CustomerGoods"]));
            }
            set {
                this["CustomerGoods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string CompReport_Goods {
            get {
                return ((string)(this["CompReport_Goods"]));
            }
            set {
                this["CompReport_Goods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string CompReport_Factors {
            get {
                return ((string)(this["CompReport_Factors"]));
            }
            set {
                this["CompReport_Factors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string Visitors {
            get {
                return ((string)(this["Visitors"]));
            }
            set {
                this["Visitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string Visitors_Customers {
            get {
                return ((string)(this["Visitors_Customers"]));
            }
            set {
                this["Visitors_Customers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string Faktor_Customer {
            get {
                return ((string)(this["Faktor_Customer"]));
            }
            set {
                this["Faktor_Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ReturnFactors_Visitors {
            get {
                return ((string)(this["ReturnFactors_Visitors"]));
            }
            set {
                this["ReturnFactors_Visitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string BuyReport_Customer {
            get {
                return ((string)(this["BuyReport_Customer"]));
            }
            set {
                this["BuyReport_Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string BuyReport_Goods {
            get {
                return ((string)(this["BuyReport_Goods"]));
            }
            set {
                this["BuyReport_Goods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string CompReport_Factor {
            get {
                return ((string)(this["CompReport_Factor"]));
            }
            set {
                this["CompReport_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string CompReport_Goods1 {
            get {
                return ((string)(this["CompReport_Goods1"]));
            }
            set {
                this["CompReport_Goods1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ReturnBuyReport_Customer {
            get {
                return ((string)(this["ReturnBuyReport_Customer"]));
            }
            set {
                this["ReturnBuyReport_Customer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ExtraReduction1 {
            get {
                return ((string)(this["ExtraReduction1"]));
            }
            set {
                this["ExtraReduction1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string MarginReport {
            get {
                return ((string)(this["MarginReport"]));
            }
            set {
                this["MarginReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string GoodCustomerFactor {
            get {
                return ((string)(this["GoodCustomerFactor"]));
            }
            set {
                this["GoodCustomerFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ReturnBuyReport_Good {
            get {
                return ((string)(this["ReturnBuyReport_Good"]));
            }
            set {
                this["ReturnBuyReport_Good"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool baha {
            get {
                return ((bool)(this["baha"]));
            }
            set {
                this["baha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string GoodReportByVisitors {
            get {
                return ((string)(this["GoodReportByVisitors"]));
            }
            set {
                this["GoodReportByVisitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExportSanad {
            get {
                return ((bool)(this["ShowExportSanad"]));
            }
            set {
                this["ShowExportSanad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtraMethod {
            get {
                return ((bool)(this["ExtraMethod"]));
            }
            set {
                this["ExtraMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string GoodReportByGroup {
            get {
                return ((string)(this["GoodReportByGroup"]));
            }
            set {
                this["GoodReportByGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ProfitReportByGoodGroup {
            get {
                return ((string)(this["ProfitReportByGoodGroup"]));
            }
            set {
                this["ProfitReportByGoodGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ProfitReportByVisitors {
            get {
                return ((string)(this["ProfitReportByVisitors"]));
            }
            set {
                this["ProfitReportByVisitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chk_Net {
            get {
                return ((bool)(this["chk_Net"]));
            }
            set {
                this["chk_Net"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyBaha {
            get {
                return ((bool)(this["BuyBaha"]));
            }
            set {
                this["BuyBaha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chk_ByuNet {
            get {
                return ((bool)(this["chk_ByuNet"]));
            }
            set {
                this["chk_ByuNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyAggregationSaleDoc {
            get {
                return ((bool)(this["BuyAggregationSaleDoc"]));
            }
            set {
                this["BuyAggregationSaleDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tax {
            get {
                return ((decimal)(this["tax"]));
            }
            set {
                this["tax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal taxes {
            get {
                return ((decimal)(this["taxes"]));
            }
            set {
                this["taxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal buytax {
            get {
                return ((decimal)(this["buytax"]));
            }
            set {
                this["buytax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal buytaxes {
            get {
                return ((decimal)(this["buytaxes"]));
            }
            set {
                this["buytaxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1393/01/01-1393/12/29")]
        public string ViewSettelSaleFactors {
            get {
                return ((string)(this["ViewSettelSaleFactors"]));
            }
            set {
                this["ViewSettelSaleFactors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool giftOrder {
            get {
                return ((bool)(this["giftOrder"]));
            }
            set {
                this["giftOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PCBed {
            get {
                return ((bool)(this["PCBed"]));
            }
            set {
                this["PCBed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PCBes {
            get {
                return ((bool)(this["PCBes"]));
            }
            set {
                this["PCBes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SalePCBed {
            get {
                return ((bool)(this["SalePCBed"]));
            }
            set {
                this["SalePCBed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SalePCBes {
            get {
                return ((bool)(this["SalePCBes"]));
            }
            set {
                this["SalePCBes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaleGoodACCNum {
            get {
                return ((bool)(this["SaleGoodACCNum"]));
            }
            set {
                this["SaleGoodACCNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuyGoodACCNum {
            get {
                return ((bool)(this["BuyGoodACCNum"]));
            }
            set {
                this["BuyGoodACCNum"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=P-RDP\\PERP2017;Initial Catalog=PBASE_13;Persist Security Info=True;Us" +
            "er ID=sa;Password=Pars@63")]
        public string BASE {
            get {
                //return ((string)(this["BASE"]));
                return Class_ChangeConnectionString.SetConnection("PBASE");
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=P-RDP\\PERP2017;Initial Catalog=PACNT_13_1399;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=Pars@63")]
        public string ACNT {
            get {
                //return ((string)(this["ACNT"]));
                return Class_ChangeConnectionString.SetConnection("PACNT");

            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=P-RDP\\PERP2017;Initial Catalog=PWHRS_13_1399;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=Pars@63")]
        public string WHRS {
            get {
                //return ((string)(this["WHRS"]));
                return Class_ChangeConnectionString.SetConnection("PWHRS");

            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=P-RDP\\PERP2017;Initial Catalog=PBANK_13_1399;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=Pars@63")]
        public string BANK {
            get {
                //return ((string)(this["BANK"]));
                return Class_ChangeConnectionString.SetConnection("PBANK");

            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=P-RDP\\PERP2017;Initial Catalog=PSALE_13_1399;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=Pars@63")]
        public string SALE {
            get {
                //return ((string)(this["SALE"]));
                return Class_ChangeConnectionString.SetConnection("PSALE");

            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSaleFactorSentence {
            get {
                return ((bool)(this["ShowSaleFactorSentence"]));
            }
            set {
                this["ShowSaleFactorSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string BackupPath {
            get {
                return ((string)(this["BackupPath"]));
            }
            set {
                this["BackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaeedSefareshat {
            get {
                return ((bool)(this["TaeedSefareshat"]));
            }
            set {
                this["TaeedSefareshat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowMojodi {
            get {
                return ((bool)(this["ShowMojodi"]));
            }
            set {
                this["ShowMojodi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FactorPrice {
            get {
                return ((int)(this["FactorPrice"]));
            }
            set {
                this["FactorPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int barcodeprint {
            get {
                return ((int)(this["barcodeprint"]));
            }
            set {
                this["barcodeprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string Statuse {
            get {
                return ((string)(this["Statuse"]));
            }
            set {
                this["Statuse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string BankId {
            get {
                return ((string)(this["BankId"]));
            }
            set {
                this["BankId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Saler {
            get {
                return ((string)(this["Saler"]));
            }
            set {
                this["Saler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TypeSale {
            get {
                return ((string)(this["TypeSale"]));
            }
            set {
                this["TypeSale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BankPose {
            get {
                return ((string)(this["BankPose"]));
            }
            set {
                this["BankPose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TypSeachDoc {
            get {
                return ((string)(this["TypSeachDoc"]));
            }
            set {
                this["TypSeachDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BankName {
            get {
                return ((string)(this["BankName"]));
            }
            set {
                this["BankName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Hesab_Bank {
            get {
                return ((string)(this["Hesab_Bank"]));
            }
            set {
                this["Hesab_Bank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BayerName {
            get {
                return ((string)(this["BayerName"]));
            }
            set {
                this["BayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Returnfunction {
            get {
                return ((string)(this["Returnfunction"]));
            }
            set {
                this["Returnfunction"] = value;
            }
        }
    }
}
