//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSALE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=PSALE_XX_XXXX;Integrated Security=True")]
        public string PSALE_ConnectionString {
            get {
                if (Class_ChangeConnectionString.CurrentConnection == null)
                    return ((string)(this["PSALE_ConnectionString"]));
                else
                {
                    return Class_ChangeConnectionString.CurrentConnection;
                }
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=PERP_Base;Integrated Security=True")]
        public string PERP_ConnectionString {
            get {
                if (Class_ChangeConnectionString.CurrentConnection == null)
                    return ((string)(this["PERP_ConnectionString"]));
                else
                {
                    System.Data.SqlClient.SqlConnection Con = new System.Data.SqlClient.SqlConnection(Class_ChangeConnectionString.CurrentConnection);
                    string Db = Con.Database;
                    string Connection = Class_ChangeConnectionString.CurrentConnection.Replace(Db, "PERP_Base");
                    return Connection;
                }
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=PACNT;Integrated Security=True")]
        public string PACNT_ConnectionString {
            get {
                if (Class_ChangeConnectionString.CurrentConnection == null)
                    return ((string)(this["PACNT_ConnectionString"]));
                else
                {
                    System.Data.SqlClient.SqlConnection Con = new System.Data.SqlClient.SqlConnection(Class_ChangeConnectionString.CurrentConnection);
                    string Db = Con.Database;
                    string Connection = Class_ChangeConnectionString.CurrentConnection.Replace(Db,"PACNT"+Db.Remove(0,5));
                    return Connection;
                }
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=PWHRS_XX_XXXX;Integrated Security=True")]
        public string PWHRS_ConnectionString {
            get {
                if (Class_ChangeConnectionString.CurrentConnection == null)
                    return ((string)(this["PWHRS_ConnectionString"]));
                else
                {
                    System.Data.SqlClient.SqlConnection Con = new System.Data.SqlClient.SqlConnection(Class_ChangeConnectionString.CurrentConnection);
                    string Db = Con.Database;
                    string Connection = Class_ChangeConnectionString.CurrentConnection.Replace(Db, "PWHRS" + Db.Remove(0, 5));
                    return Connection;
                }
            }
        }
    }
}
